<a href="https://colab.research.google.com/github/youngbull23/Data-Science-/blob/main/Richard_Lab_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
np.random.permutation(52)

array([ 0, 13, 41, 47, 38,  6, 50, 10, 30, 21, 34, 15, 33,  5, 40,  8, 49,
       11, 36, 26,  4, 25, 39, 42,  7,  1, 44,  9, 17, 46, 37, 22, 29, 51,
       32, 35,  2, 18, 27, 45, 12,  3, 48, 31, 28, 24, 20, 43, 16, 14, 23,
       19])

In [ ]:
cards=np.random.permutation(52)

In [ ]:
cards[0] # Queens 12, Kings 13 

14

<img src='http://www.milefoot.com/math/discrete/counting/images/cards.png'>

In [ ]:
np.arange(52).reshape(4,13) 

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38],
       [39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51]])

In [ ]:
np.arange(52).reshape(4,13)%13

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [ ]:
np.arange(52).reshape(4,13)//13 

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]])

In [ ]:
suits = ['clubs','spades','hearts','Diamonds']
names = ['ace','two','three','four','five','six','seven','eight','nine','ten','jack','queen','king']

In [ ]:
def card_name(card_number): 

    suit = card_number//13
    name = card_number%13

    return names[name] +'of'+ suits[suit]

In [ ]:
card_name(0) # Big Joker 50

'aceofclubs'

In [ ]:
card_name(51) # Jacks 10 

'kingofDiamonds'

In [ ]:
cards = np.random.permutation(52)

In [ ]:
top_of_deck          = card_name(cards[0])
second_card_in_deck  = card_name(cards[1])
last_card_in_deck    = card_name(cards[-1])
 

In [ ]:
top_of_deck,second_card_in_deck,last_card_in_deck

('queenofspades', 'sixofspades', 'aceofDiamonds')

In [ ]:
for i in range(5):
    print(card_name(cards[i]))

queenofspades
sixofspades
queenofDiamonds
fourofDiamonds
nineofclubs


In [ ]:
for i in range(15): 
    print(card_name(cards[i])) 

In [ ]:
from IPython.core.display import display, HTML

In [ ]:
def show_img(img):
  display(HTML('<img src=' + img + '>'))

In [ ]:
img = card_url_head + suit[i] + card[j] + card_url_tail